### ISSUE TITLE
Error calling ##F

### ISSUE THREAD

**Issue by gavr123456789** [francholi/libtcc_demo#1]
Arch linux, TCC: 0.9.27-3
```shell
❯❯❯ ./compile.sh
❯❯❯ ./main  
Renderer: GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL version 4.5.0 NVIDIA 440.44
<string>:54: error: field not found: counter
Error calling ##F
Error calling ##F
Error calling ##F
...
non stop spam
```

**Comment by francholi** [comment]
Hey, this code was for demonstration of a technique only, is a not a "project" I maintain. It's been a year since I don't read this code, and assume that you only cloned/downloaded the code, you did not change anything and this is the output you got?

Give me couple of days, that my chemo round wears off and I will check here in my computer and come back to you.

**Comment by francholi** [comment]
Ok, I am bored :)  so I looked into it.
 
Something silly, I forgot that at some point I removed a field from the global state struct that is shared across any "hot reloaded" module, so that "counter" symbol was missing in the global_state_def.h file inside the GlobalState struct. 
You do not see a compilation error, when running compile.sh, because the file level0.c is not compiled in advance, is compiled dynamically by TCC directly into memory and the symbols are redirected in main so that the new versions of the function calls can be used.
It is very fragile, probably you will break it more often than expected, but it is a good exercise when you understand how it works, the "why" it breaks. The concept could be extended to be made more robust.

Please read the README and then shoot any questions you may have about the code and I will try to explain.

For rendering, the vertex shader just passes 4 vertices and 4 uv's (a full screen quad), and the pixel shader does a super simple ray traced sphere. So if you change for instance glClear value in level0.c, you wont see a difference because the quad is full screen and the background is invisible :)
To see a change in the background colour simply change the colour returned in the fragment shader when the ray misses the sphere.
I hope this clarifies some..., you can send questions directly to flopezluro@gmail.com.

**Comment by gavr123456789** [comment]
@francholi Nice! Thanks for ur time.  
![Peek 2020-01-29 17-19](https://user-images.githubusercontent.com/30507409/73364436-a69f5980-42bb-11ea-81d8-b642e55e735f.gif)
PS I found this repository, and I wanted to do something similar on Vala. But so far, I can't even get a simple hello world.  
got 
```
❯ ./build/exec
tcc: error: library 'c' not found
tcc: error: file 'crtn.o' not found
```
Do you happen to know what this might be related to?
[vala code](https://gitlab.com/gavr123456789/vala-ttc-example/blob/master/v.vala)
[c ](https://gitlab.com/gavr123456789/vala-ttc-example/blob/master/build/exec@exe/v.c#L35)

**Comment by francholi** [comment]
Hi, I have never seen Vala code before, I do not know how is the tool chain, how you link with C libraries and so on... from your comment I understand you generate C code (from vala) and then compile the final result.

Have you managed to link against any C library before from Vala?, do you need any special step? I guess that bit works because you are using libtcc :)
You can add libraries via the libtcc state API, before the linking (I would say in this case before compiling), maybe you have to link some extra stuff (libc, libcrt...) to make a proper complete main program to run, I am not sure.

Furthermore, have you tried with a simpler C code (with libtcc), without a main, just a dummy function, and try calling that function?, it feels like the main you are calling is missing some C runtime (crtn.o) but I am not sure because I have never done a C main() from a C program (or vala in your case). 

I always compile small libs and use them directly, but I guess what you are trying to do should work (you are missing something but I not sure if it is something missing when linking and building your vala program or if there is something missing when compiling the C code from libtcc (probably the latter)
I would probably try to replicate your exact code in C first (without Vala), and see if it is still complaining about these crt and c libs, then we know is something related to libtcc internal linking process of a "main" program.

cheers!

**Comment by gavr123456789** [comment]
Yes, Vala is a compiler for the glib object system (GTK)(and my favorite language ^^), the output is the most common C, so linking is no different from C. Compiles everything using meson, you can see the specific command for cc [here](https://gitlab.com/gavr123456789/vala-ttc-example/blob/master/build/compile_commands.json).  
  
Now I will try to make a code With no vala, but I assure you the problem is on the C side.  
But I know for sure it already worked in 2011 xd. https://fabiand.github.io/posts/51491969572.html

**Comment by francholi** [comment]
Ok,

From the link you provided, I can see the code receives a base dir with an
include and link directories for includes and linking.

I think the set_lib_path is your key here. Check the libtcc files, where
they are installed if you see any files related to those missing libs.

...
s.add_include_path (args[1] + "/include");
s.add_include_path ("/usr/include/");
s.set_lib_path (args[1]);
...

**Comment by gavr123456789** [comment]
I switched vala to the posix(libc) profile. So now there is no glib.h, only standard C libraries. I also turned off debag which substituted preprocessor inserts of vala code line numbers in C code for greater readability.  
  
So [here's](https://gitlab.com/gavr123456789/vala-ttc-example/blob/master/buildrelease/exec@exe/v.c) the С code.  
And [here](https://gitlab.com/gavr123456789/vala-ttc-example/blob/master/buildrelease/compile_commands.json) is the compilation command(it does not change)

**Comment by gavr123456789** [comment]
> I think the set_lib_path is your key here.  
  
Okay, I'll check it out tonight. Ty
